// Inicialização da EEPROM ----------------------------------------------------
#define POSEE1 0x0A // Início do Bloco 1 (Endereço 10)
#define POSEE2 0x5C // Início do Bloco 2 (Endereço 92)
#define POSEE3 0xAE // Início do Bloco 3 (Endereço 174)

#define POSEE_SETPOINT 0
#define POSEE_SETPOINT_OBRIGA 4
#define POSEE_VALOR_CONTADOR 8
#define POSEE_VALOR_ULTIMA_CONFERENCIA 12

#define SETPOINT_DEFAULT 100
#define SETPOINT_OBRIGA_DEFAULT 200
#define VALOR_CONTADOR_DEFAULT 0
#define VALOR_ULTIMA_CONFERENCIA_DEFAULT 0 

#rom int32 0x2100 + POSEE1 + POSEE_SETPOINT = {SETPOINT_DEFAULT }
#rom int32 0x2100 + POSEE1 + POSEE_SETPOINT_OBRIGA = {SETPOINT_OBRIGA_DEFAULT }
#rom int32 0x2100 + POSEE1 + POSEE_VALOR_CONTADOR = {VALOR_CONTADOR_DEFAULT }
#rom int32 0x2100 + POSEE1 + POSEE_VALOR_ULTIMA_CONFERENCIA = {VALOR_ULTIMA_CONFERENCIA_DEFAULT }

#rom int32 0x2100 + POSEE2 + POSEE_SETPOINT = {SETPOINT_DEFAULT }
#rom int32 0x2100 + POSEE2 + POSEE_SETPOINT_OBRIGA = {SETPOINT_OBRIGA_DEFAULT }
#rom int32 0x2100 + POSEE2 + POSEE_VALOR_CONTADOR = {VALOR_CONTADOR_DEFAULT }
#rom int32 0x2100 + POSEE2 + POSEE_VALOR_ULTIMA_CONFERENCIA = {VALOR_ULTIMA_CONFERENCIA_DEFAULT }

#rom int32 0x2100 + POSEE3 + POSEE_SETPOINT = {SETPOINT_DEFAULT }
#rom int32 0x2100 + POSEE3 + POSEE_SETPOINT_OBRIGA = {SETPOINT_OBRIGA_DEFAULT }
#rom int32 0x2100 + POSEE3 + POSEE_VALOR_CONTADOR = {VALOR_CONTADOR_DEFAULT }
#rom int32 0x2100 + POSEE3 + POSEE_VALOR_ULTIMA_CONFERENCIA = {VALOR_ULTIMA_CONFERENCIA_DEFAULT }
