/*
 * defines.h
 *
 *  Created on: Apr 1, 2026
 *      Author: Lucas
 */

#ifndef INC_DEFINES_H_
#define INC_DEFINES_H_

#include "stm32f4xx_hal.h"
#include <stdint.h>
#include <stdbool.h>
#include "main.h"

// display
#define SEG_A_PIN GPIO_PIN_5
#define SEG_A_GPIO_PORT GPIOA
#define SEG_B_PIN GPIO_PIN_6
#define SEG_B_GPIO_PORT GPIOA
#define SEG_C_PIN GPIO_PIN_7
#define SEG_C_GPIO_PORT GPIOA
#define SEG_D_PIN GPIO_PIN_4
#define SEG_D_GPIO_PORT GPIOC
#define SEG_E_PIN GPIO_PIN_5
#define SEG_E_GPIO_PORT GPIOC
#define SEG_F_PIN GPIO_PIN_0
#define SEG_F_GPIO_PORT GPIOB
#define SEG_G_PIN GPIO_PIN_1
#define SEG_G_GPIO_PORT GPIOB
#define SEG_DP_PIN GPIO_PIN_2
#define SEG_DP_GPIO_PORT GPIOB


// PC6_DISPLAY_UNIDADE_GPIO_Port
#define DISPLAY_UNIDADE PC6_DISPLAY_UNIDADE_Pin
#define DISPLAY_UNIDADE_PORT PC6_DISPLAY_UNIDADE_GPIO_Port
#define DISPLAY_DEZENA PB15_DISPLAY_DEZENA_Pin
#define DISPLAY_DEZENA_PORT PB15_DISPLAY_DEZENA_GPIO_Port
#define DISPLAY_CENTENA PB14_DISPLAY_CENTENA_Pin
#define DISPLAY_CENTENA_PORT PB14_DISPLAY_CENTENA_GPIO_Port
#define DISPLAY_MILHAR_UNIDADE PB13_DISPLAY_UNIDADE_MILHAR_Pin
#define DISPLAY_MILHAR_UNIDADE_PORT PB13_DISPLAY_UNIDADE_MILHAR_GPIO_Port  
#define DISPLAY_MILHAR_DEZENA PB12_DISPLAY_DEZENA_MILHAR_Pin
#define DISPLAY_MILHAR_DEZENA_PORT PB12_DISPLAY_DEZENA_MILHAR_GPIO_Port
#define DISPLAY_MILHAR_CENTENA PB10_DISPLAY_CENTENA_MILHAR_Pin
#define DISPLAY_MILHAR_CENTENA_PORT PB10_DISPLAY_CENTENA_MILHAR_GPIO_Port

// botões
#define BOTAO_RELOGIO PC1_PIN_INPUT_MEMBRANA_01_Pin
#define BOTAO_RELOGIO_PORT PC1_PIN_INPUT_MEMBRANA_01_GPIO_Port
#define BOTAO_MIN PC2_PIN_INPUT_MEMBRANA_02_Pin
#define BOTAO_MIN_PORT PC2_PIN_INPUT_MEMBRANA_02_GPIO_Port
#define BOTAO_MAX PC3_PIN_INPUT_MEMBRANA_03_Pin
#define BOTAO_MAX_PORT PC3_PIN_INPUT_MEMBRANA_03_GPIO_Port

#define TURBO_LEVEL1 7
#define TURBO_LEVEL2 5
#define TURBO_LEVEL3 3

// entradas digitais
#define INPUT_01 PB8_PIN_ENTRADA_01_Pin
#define INPUT_01_PORT PB8_PIN_ENTRADA_01_GPIO_Port
// #define INPUT_02 PB9_INPUT_02_Pin
// #define INPUT_02_PORT PB9_INPUT_02_GPIO_Port

// leds
#define LED_01 PC10_pOutDig_LedSts1_Pin
#define LED_01_PORT PC10_pOutDig_LedSts1_GPIO_Port
#define LED_02 PC11_pOutDig_LedSts2_Pin
#define LED_02_PORT PC11_pOutDig_LedSts2_GPIO_Port
#define LED_03 PC12_pOutDig_LedSts3_Pin
#define LED_03_PORT PC12_pOutDig_LedSts3_GPIO_Port
#define LED_04 PC13_pOutDig_LedSts4_Pin
#define LED_04_PORT PC13_pOutDig_LedSts4_GPIO_Port

// Saídas digitais
// #define RELE_01 PC7_PIN_SAIDA_DIGITAL1_Pin
// #define RELE_01_PORT PC7_PIN_SAIDA_DIGITAL1_GPIO_Port
// #define RELE_02 PC9_PIN_SAIDA_DIGITAL2_Pin
// #define RELE_02_PORT PC9_PIN_SAIDA_DIGITAL2_GPIO_Port

// Outras definições
#define HIGH GPIO_PIN_SET
#define LOW GPIO_PIN_RESET



#endif /* INC_DEFINES_H_ */
